runtime: custom
env: flex
entrypoint: node server.js
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 10
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "22"